project_id = "lljqptscpeamwfkzsezo"

[functions.create-family]
verify_jwt = false

[functions.join-family]
verify_jwt = false

[functions.fetch-meetings]
verify_jwt = false

[functions.expire-location-request]
verify_jwt = false

[functions.check-liquor-license]
verify_jwt = false

[functions.extract-branding]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.create-square-checkout]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false

[functions.apply-coupon]
verify_jwt = false

[functions.create-organization]
verify_jwt = false

[functions.create-family-checkout]
verify_jwt = false

[functions.apply-family-coupon]
verify_jwt = false

[functions.create-family-group]
verify_jwt = false

[functions.check-overdue-checkouts]
verify_jwt = false

[functions.create-moderator]
verify_jwt = false

[functions.request-temp-moderator]
verify_jwt = false

[functions.send-family-invite]
verify_jwt = false

[functions.create-moderator-checkout]
verify_jwt = false

[functions.verify-super-admin]
verify_jwt = false

[functions.get-admin-stats]
verify_jwt = false
