project_id = "lljqptscpeamwfkzsezo"

[functions.create-family]
verify_jwt = false

[functions.join-family]
verify_jwt = false

[functions.fetch-meetings]
verify_jwt = false

[functions.expire-location-request]
verify_jwt = false

[functions.check-liquor-license]
verify_jwt = false

[functions.extract-branding]
verify_jwt = false

[functions.square-webhook]
verify_jwt = false

[functions.create-square-checkout]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false
